name: sem3
channels:
  - anaconda
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - intel-openmp=2019.4=243
  - joblib=0.13.2=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - numpy-base=1.17.2=py37hde5b4d6_0
  - openssl=1.1.1d=h7b6447c_2
  - pandas=0.25.1=py37he6710b0_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.3=py_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.21.3=py37hd81dba3_0
  - scipy=1.3.1=py37h7c811a0_0
  - setuptools=41.0.1=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.8.1
    - astor==0.8.0
    - astpretty==1.6.0
    - chardet==3.0.4
    - configargparse==0.14.0
    - future==0.17.1
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.24.1
    - h5py==2.10.0
    - idna==2.8
    - jsonlines==1.2.0
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - numpy==1.17.2
    - opt-einsum==3.1.0
    - pip==19.2.3
    - protobuf==3.10.0
    - pyyaml==5.1.2
    - requests==2.22.0
    - six==1.12.0
    - tensorboard==2.0.0
    - tensorflow-estimator==2.0.0
    - tensorflow-gpu==2.0.0
    - termcolor==1.1.0
    - torch==1.2.0
    - torchtext==0.4.0
    - tqdm==4.30.0
    - urllib3==1.25.3
    - werkzeug==0.16.0
    - wrapt==1.11.2
prefix: /home/rhaldar2/anaconda3/envs/sem3

